apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels: 
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
            valueFrom:
              secretKeyRef: 
                name: mongodb-secret
                key: root-username-mongodb 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            valueFrom:
              secretKeyRef: 
                name: mongodb-secret
                key: root-password-mongodb
          - name: ME_CONFIG_MONGODB_SERVER 
            valueFrom:
              configMapKeyRef: 
                name: mongo-express-config
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
      





